### ISSUE TITLE
Pheanstalk version

### ISSUE THREAD

**Issue by zmicier** [nickurt/beanstalkd-ui#3]
Starting from October 14, SlmQueue/SlmQueueBeanstalkd requries "pda/pheanstalk": "~3.0" so we have a conflict here as this library still require "pda/pheanstalk": "2.*".

**Comment by zmicier** [comment]
As far as I can see just PheanstalkFactory.php must fixed along with composer.json (now pheanstalk uses proper php namespaces).

**Comment by nickurt** [comment]
Thanks for the heads-up, I will release a fixed/updated version this weekend

**Comment by nickurt** [comment]
Seems to be working all, can you checkout develop branch for latest changes

    php composer.phar require nickurt/beanstalkd-ui:dev-develop

When you don't have problems, I can merge it back to master and create a new tag for it

**Comment by nickurt** [comment]
Ping @zmicier, worked for you?

**Comment by nickurt** [comment]
Fixed in v0.1.1 (or use latest from dev-master)
